version: 0.{build}
image: Visual Studio 2019
branches:
  only:
  - master
configuration: Release
build:
  project: FalloutStrategy/Fallout_Strategy.sln
  verbosity: minimal
after_build:
- cmd: >-
    copy C:\projects\automatic-builds\FalloutStrategy\Release\Fallout_Strategy.exe C:\projects\automatic-builds\FalloutStrategy\Game\
    copy C:\projects\automatic-builds\README.md C:\projects\automatic-builds\FalloutStrategy\Game\
artifacts:
- path: FalloutStrategy/Game
  name: Fallout_Strategy
  type: WebDeployPackage
deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Fallout Test v$(appveyor_build_version)
  description: Automatic Release
  auth_token:
    secure: M8iNekkgCAijnlmChSFFh34jRjsb1NkrcsN3vDOwgyfz7kn1mEzKyvzt0Tb1hZ+H
  draft: false
  prerelease: false
notifications:
- provider: GitHubPullRequest
  template: Release Successful
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
