version: 0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
platform: x86
shallow_clone: true
build:
  project: FalloutStrategy/Fallout_Strategy.sln
  verbosity: minimal
artifacts:
- path: FalloutStrategy/Game
  name: Fallout_Strategy
deploy:
- provider: GitHub
  tag: v0.{build]
  release: Fallout Strategy
  auth_token:
    secure: H6B9/bnDdrJuQZpksnC5SA==
  artifact: FalloutStrategy/Game
  draft: true